name: shm

channels:
- conda-forge

dependencies:
# Do not fix py version. When installing Conda, I attached Py 3.10 with Conda for other progranmes (e. g. VS Code); so, maybe avoid fixing a certain Py version.
- python
- ipython
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- chaospy
- pip
- oct2py
- pytest
- pip:
  - flake8
  - black

